name: PR Checks

on:
  pull_request:
    branches:
      - main

jobs:
  pr-checks:
    name: PR Validation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Setup pnpm  # ✅ Correct way to install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8  # Adjust version if needed

      - name: Verify pnpm installation
        run: pnpm --version  # ✅ Check if pnpm is available

      - name: Install dependencies
        run: pnpm install

      - name: Run Lint
        run: pnpm run lint

      - name: Run Tests
        run: pnpm test -- --coverage

      - name: Build Application
        run: pnpm run build
